/**
 * Clarification API client (T202 + T208 + T602).
 *
 * Wraps the FastAPI clarification endpoints used by the candidate/profile
 * visualisation UI and the employer-side talent-image UI:
 *   - POST /api/clarification/synthesize        → run the multi-step LLM pipeline
 *   - GET  /api/clarification/my-profile        → fetch the persisted record
 *   - POST /api/clarification/synthesize-employer → employer counterpart
 *   - GET  /api/clarification/role/{role_id}    → employer record
 *
 * The shapes below mirror the JSON contract produced by
 * backend/agents/jobseeker/clarifier_agent.py — see the record that agent
 * upserts into `candidate_clarifications` for the field list.
 */

import { createClient } from "@/lib/supabase";

// ---------------------------------------------------------------------------
// Types — must stay in sync with candidate_clarifications table columns
// ---------------------------------------------------------------------------

export type SourceLabel =
  | "profile"
  | "journals"
  | "conversations"
  | "emotion_history"
  | "cv"
  | "agent_inference"
  | "unknown";

export type Priority = "high" | "medium" | "low";

/** A value with provenance metadata — produced by the LLM for each insight. */
export interface AttributedValue<T = string> {
  value: T;
  reasoning?: string;
  confidence?: number;
  sources?: SourceLabel[];
}

/** Conflict between two data sources — what the agent flags in `conflict_flags`. */
export interface Contradiction {
  source_a: string;
  source_b: string;
  explanation: string;
  /** Optional: the actual fields that disagree. */
  fields?: string[];
}

/** A follow-up question generated by the agent to close an info gap. */
export interface FollowUpQuestion {
  question: string;
  priority: Priority;
  purpose: string;
  /** Whether the user has already answered (locally merged from clarifications). */
  answered?: boolean;
  /** When answered, the answer text. */
  answer?: string | null;
}

/** The `profile_synthesis` JSON column. */
export interface ProfileSynthesis {
  summary?: AttributedValue<string>;
  explicit_skills?: AttributedValue[];
  implicit_traits?: AttributedValue[];
  value_orientation?: AttributedValue[];
  career_interests?: AttributedValue[];
  [key: string]: unknown;
}

/** A persisted candidate_clarifications row. */
export interface CandidateClarification {
  id?: string;
  user_id?: string;
  candidate_id?: string | null;
  profile_synthesis?: ProfileSynthesis;
  explicit_needs?: unknown[];
  implicit_needs?: unknown[];
  must_haves?: unknown[];
  nice_to_haves?: unknown[];
  deal_breakers?: unknown[];
  conflict_flags?: Contradiction[];
  follow_up_questions?: FollowUpQuestion[];
  confidence_score?: number;
  info_completeness?: number;
  last_synthesized_at?: string;
  created_at?: string;
  updated_at?: string;
}

/** The return shape of POST /api/clarification/synthesize. */
export interface SynthesizeResponse {
  text: string;
  synthesis: {
    profile_synthesis?: ProfileSynthesis;
    real_needs?: {
      explicit?: unknown[];
      implicit?: unknown[];
      must_haves?: unknown[];
      nice_to_haves?: unknown[];
      deal_breakers?: unknown[];
    };
    contradictions?: Contradiction[];
    follow_up_questions?: FollowUpQuestion[];
    info_completeness?: AttributedValue<number> | number;
    overall_confidence?: number;
    reflection?: {
      issues?: string[];
      corrections?: Record<string, unknown>;
      confidence_after_reflection?: number;
    };
    reasoning_chain?: string[];
  };
}

// ---------------------------------------------------------------------------
// HTTP plumbing
// ---------------------------------------------------------------------------

const API_BASE =
  process.env.NEXT_PUBLIC_API_URL?.replace(/\/$/, "") || "http://localhost:8000";

async function authHeaders(): Promise<HeadersInit> {
  // Prefer supabase session; fall back to the legacy sb_token localStorage
  // entry that the realtime chat stores.
  try {
    const supabase = createClient();
    const { data } = await supabase.auth.getSession();
    const token = data.session?.access_token;
    if (token) return { Authorization: `Bearer ${token}` };
  } catch {
    /* fall through */
  }
  if (typeof window !== "undefined") {
    const legacy = window.localStorage.getItem("sb_token");
    if (legacy) return { Authorization: `Bearer ${legacy}` };
  }
  return {};
}

async function request<T>(
  path: string,
  init: RequestInit = {},
): Promise<T> {
  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...((await authHeaders()) as Record<string, string>),
    ...((init.headers as Record<string, string>) ?? {}),
  };

  const res = await fetch(`${API_BASE}${path}`, { ...init, headers });
  if (!res.ok) {
    let body: unknown;
    try {
      body = await res.json();
    } catch {
      body = await res.text();
    }
    throw new Error(
      `Clarification API ${res.status} ${res.statusText}: ${JSON.stringify(body)}`,
    );
  }
  if (res.status === 204) return undefined as T;
  return (await res.json()) as T;
}

// ---------------------------------------------------------------------------
// Client
// ---------------------------------------------------------------------------

export const clarificationApi = {
  /**
   * Run the multi-step LLM pipeline (synthesize → reflect → persist).
   * Returns the agent's freeform reply + the structured synthesis object.
   */
  synthesize(): Promise<SynthesizeResponse> {
    return request<SynthesizeResponse>("/api/clarification/synthesize", {
      method: "POST",
      body: JSON.stringify({}),
    });
  },

  /** Persisted candidate clarification row (may be empty `{}` if never run). */
  myProfile(): Promise<CandidateClarification> {
    return request<CandidateClarification>("/api/clarification/my-profile", {
      method: "GET",
      cache: "no-store",
    });
  },

  // ----- Employer side (kept here so the same client can drive both) -----

  synthesizeEmployer(body: {
    role_id: string;
    brief?: Record<string, unknown>;
    spec?: Record<string, unknown>;
    compliance?: Record<string, unknown>;
    policy?: Record<string, unknown>;
  }): Promise<{ text: string; summary: Record<string, unknown> }> {
    return request<{ text: string; summary: Record<string, unknown> }>(
      "/api/clarification/synthesize-employer",
      { method: "POST", body: JSON.stringify(body) },
    );
  },

  roleClarification(roleId: string): Promise<Record<string, unknown>> {
    return request<Record<string, unknown>>(
      `/api/clarification/role/${encodeURIComponent(roleId)}`,
      { method: "GET", cache: "no-store" },
    );
  },
};

// ---------------------------------------------------------------------------
// Helpers — coerce the heterogeneous shapes into display-friendly values.
// The LLM may return either plain strings OR `AttributedValue` objects for
// needs fields, so normalise before rendering.
// ---------------------------------------------------------------------------

export type NormalisedItem = {
  text: string;
  reasoning?: string;
  confidence?: number;
  sources?: SourceLabel[];
};

function normaliseOne(item: unknown): NormalisedItem | null {
  if (item == null) return null;
  if (typeof item === "string") return { text: item };
  if (typeof item === "object") {
    const obj = item as Record<string, unknown>;
    const value = (obj.value ?? obj.text ?? obj.label ?? obj.name) as
      | string
      | undefined;
    if (!value) return null;
    return {
      text: String(value),
      reasoning: (obj.reasoning as string | undefined) ?? undefined,
      confidence: typeof obj.confidence === "number" ? obj.confidence : undefined,
      sources: Array.isArray(obj.sources)
        ? (obj.sources as SourceLabel[])
        : undefined,
    };
  }
  return null;
}

export function normaliseList(items: unknown): NormalisedItem[] {
  if (!Array.isArray(items)) return [];
  return items
    .map(normaliseOne)
    .filter((x): x is NormalisedItem => x !== null);
}

export const NEEDS_GROUPS = [
  "must_haves",
  "nice_to_haves",
  "deal_breakers",
] as const;
export type NeedsGroup = (typeof NEEDS_GROUPS)[number];

export const NEEDS_GROUP_LABEL: Record<NeedsGroup, string> = {
  must_haves: "必须满足",
  nice_to_haves: "最好有",
  deal_breakers: "不能接受",
};

export const PRIORITY_LABEL: Record<Priority, string> = {
  high: "重要",
  medium: "建议",
  low: "可选",
};

export const PRIORITY_COLOR: Record<Priority, string> = {
  high: "bg-rose-100 text-rose-700 border-rose-200",
  medium: "bg-amber-100 text-amber-700 border-amber-200",
  low: "bg-slate-100 text-slate-600 border-slate-200",
};

export const SOURCE_LABEL: Record<SourceLabel, string> = {
  profile: "基础档案",
  journals: "工作日记",
  conversations: "智能体对话",
  emotion_history: "情绪记录",
  cv: "简历",
  agent_inference: "智能体推断",
  unknown: "其他来源",
};

export type ClarificationClient = typeof clarificationApi;

// ---------------------------------------------------------------------------
// T602: Employer-side extras (kept in the same module so the role/talent-
// image UI doesn't need a second import).
// ---------------------------------------------------------------------------

export type StakeholderRole = "boss" | "hr" | "dept_head" | "admin";

export const STAKEHOLDER_LABEL: Record<StakeholderRole, string> = {
  boss: "老板 / 决策层",
  hr: "HR",
  dept_head: "部门负责人",
  admin: "行政 / 其他",
};

export const STAKEHOLDER_COLOR: Record<StakeholderRole, string> = {
  boss: "bg-indigo-100 text-indigo-700 border-indigo-200",
  hr: "bg-sky-100 text-sky-700 border-sky-200",
  dept_head: "bg-emerald-100 text-emerald-700 border-emerald-200",
  admin: "bg-slate-100 text-slate-600 border-slate-200",
};

/** A single persona's submitted brief / spec snippet — what the consensus
 * engine sees from each side. */
export interface StakeholderStance {
  role: StakeholderRole;
  /** 0..100 — higher means the role's view aligns with the consensus. */
  alignment: number;
  summary?: string;
  /** Optional list of requirements this stakeholder emphasised. */
  emphasis?: string[];
}

/** Talent image dimensions populated by the employer clarifier agent. */
export interface TalentImage {
  hard_skills?: string[];
  soft_skills?: string[];
  experience_profile?: Record<string, string | number>;
  cultural_fit?: Record<string, string>;
  summary?: string;
}

/** A persisted employer_clarifications row. */
export interface EmployerClarification {
  id?: string;
  role_id?: string;
  talent_image?: TalentImage;
  hard_skills?: string[];
  soft_skills?: string[];
  experience_profile?: Record<string, string | number>;
  cultural_fit?: Record<string, string>;
  explicit_requirements?: unknown[];
  implicit_requirements?: unknown[];
  must_haves?: unknown[];
  nice_to_haves?: unknown[];
  contributor_inputs?: {
    brief?: Record<string, unknown>;
    spec?: Record<string, unknown>;
    compliance?: Record<string, unknown>;
    policy?: Record<string, unknown>;
  };
  conflicts?: Contradiction[] | string[];
  consensus_score?: number;
  follow_up_questions?: FollowUpQuestion[];
  last_synthesized_at?: string;
}

/** Best-effort view of one stakeholder's stance, derived from
 * `contributor_inputs`. Each side shows up even when its slot is empty. */
export function deriveStakeholderStances(
  row: EmployerClarification | null,
): StakeholderStance[] {
  if (!row?.contributor_inputs) {
    return [];
  }
  const { brief, spec, compliance, policy } = row.contributor_inputs;
  const has = (x: unknown) => {
    if (!x || typeof x !== "object") return false;
    const o = x as Record<string, unknown>;
    return Object.values(o).some(
      (v) => v != null && !(typeof v === "string" && v.length === 0),
    );
  };
  const baseline = row.consensus_score ?? 0.5;
  return [
    {
      role: "boss",
      summary: describe(brief),
      alignment: scale(has(brief), baseline),
      emphasis: pickEmphasis(brief),
    },
    {
      role: "hr",
      summary: describe({ ...(compliance ?? {}), ...(policy ?? {}) }),
      alignment: scale(has(compliance) || has(policy), baseline),
      emphasis: pickEmphasis({ ...(compliance ?? {}), ...(policy ?? {}) }),
    },
    {
      role: "dept_head",
      summary: describe(spec),
      alignment: scale(has(spec), baseline),
      emphasis: pickEmphasis(spec),
    },
  ];
}

function describe(input: Record<string, unknown> | undefined): string {
  if (!input) return "未提交";
  const summary = (input as Record<string, unknown>).summary;
  if (typeof summary === "string" && summary.trim()) return summary;
  return "已提交";
}

function pickEmphasis(input: Record<string, unknown> | undefined): string[] {
  if (!input) return [];
  const must = (input as Record<string, unknown>).must_haves;
  if (Array.isArray(must)) {
    return must
      .map((m) => (typeof m === "string" ? m : null))
      .filter((m): m is string => Boolean(m))
      .slice(0, 3);
  }
  return [];
}

function scale(hasContent: boolean, baseline: number): number {
  if (!hasContent) return 30;
  // Up to ±20 points around the consensus baseline, clamped to 0..100.
  return Math.max(0, Math.min(100, Math.round((0.6 + baseline * 0.4) * 100)));
}

/** Thin re-export of the employer endpoints for convenience. */
export const employerClarificationApi = {
  /** GET /api/clarification/role/{role_id} */
  roleClarification(roleId: string): Promise<EmployerClarification> {
    return clarificationApi.roleClarification(roleId) as Promise<EmployerClarification>;
  },

  /** POST /api/clarification/synthesize-employer */
  synthesizeEmployer(body: {
    role_id: string;
    brief?: Record<string, unknown>;
    spec?: Record<string, unknown>;
    compliance?: Record<string, unknown>;
    policy?: Record<string, unknown>;
  }) {
    return clarificationApi.synthesizeEmployer(body);
  },
};
