"""v5.0 services/integrations/ public API."""
from __future__ import annotations

from .api_key import KEY_PREFIX_LITERAL, KEY_RANDOM_BYTES, KEY_TOTAL_LEN, GeneratedKey, generate_key, VerifiedKey, verify_key, check_scope, InMemoryRateLimiter, RedisTokenBucket, RateLimitGuard, revoke, to_public, validate_scopes  # noqa: F401,F403
from .candidate_recommender import RecommendedCandidate, CandidateRecommender  # noqa: F401,F403
from .collaboration_room import ROOM_TYPES, ROOM_MEMBER_ROLES, MESSAGE_TYPES, MAX_MESSAGE_LEN, MAX_NAME_LEN, MAX_REACTIONS_PER_MESSAGE, RoomError, NotMemberError, MessageNotFoundError, PermissionDeniedError, Room, RoomMember, RoomMessage, RoomReaction, create_room, get_room, get_room_with_members, list_my_rooms, update_room, archive_room, invite_member, remove_member, leave_room, list_members, post_message, edit_message, delete_message, list_messages, list_thread_replies, search_messages, add_reaction, list_reactions, pin_message, unpin_message, list_pins, mark_read, get_unread_count, get_total_unread_count, list_my_mentions, mark_mention_read  # noqa: F401,F403
from .file_storage import DEFAULT_BUCKET, SIGNED_URL_TTL_SECONDS, FileStorageService, get_file_storage, reset_file_storage  # noqa: F401,F403
from .funnel_events import FunnelEvent, FunnelEventTracker, auto_transition  # noqa: F401,F403
from .job_subscription import DEFAULT_LIMIT, SubscriptionCriteria, JobPosting, Subscription, JobSubscriptionService  # noqa: F401,F403
from .persona_memory import PREF_KEYS, MIN_CONFIDENCE, SOURCE_EXPLICIT, SOURCE_INFERRED, SOURCE_ADMIN, set_pref, get_prefs, get_pref, delete_pref, EXTRACT_PROMPT, infer_prefs_from_text, render_prefs_for_prompt  # noqa: F401,F403
from .pii_field_encryption import FieldSpec, resolve_canonical, list_pii_fields, PIIFieldService, get_pii_field_service, pii_encrypted_fields, encrypt_dict, decrypt_dict  # noqa: F401,F403
from .pilot_invitation import DEFAULT_TOKEN_BYTES, DEFAULT_TTL_DAYS, Invitation, generate_invite_token, build_invite_url, create_invitation, accept_invitation  # noqa: F401,F403
from .pilot_service import (  # noqa: F401,F403
    NPS_TARGET,
    PROGRAM_STATUSES,
    TOP_PAIN_POINTS_LIMIT,
    WEEKLY_ACTIVE_TARGET,
    PilotReport,
    ProgramStats,
    compute_nps,
    create_program,
    end_program,
    generate_report,
    get_program,
    get_stats,
    invite,
    list_programs,
)
from .nps_service import (  # noqa: F401,F403
    CATEGORY_BUG,
    CATEGORY_COMPLAINT,
    CATEGORY_DOCS,
    CATEGORY_FEATURE,
    CATEGORY_OTHER,
    CATEGORY_PERFORMANCE,
    CATEGORY_PRAISE,
    CATEGORY_PRICING,
    SUPPORTED_CATEGORIES,
    CategorizedFeedback,
    NPSResult,
    calculate_nps,
    categorize_feedback,
    categorize_many,
)
from .pilot_report import generate_monthly_report, generate_monthly_report_text  # noqa: F401,F403
from .push_engine import PushRecord, PushEngine  # noqa: F401,F403
from .realtime_router import AGENT_DESCRIPTIONS_FALLBACK, RealtimeRouter  # noqa: F401,F403
from .transcribe import TranscribeResult, transcribe_audio  # noqa: F401,F403

__all__: list[str] = [
    "KEY_PREFIX_LITERAL",
    "KEY_RANDOM_BYTES",
    "KEY_TOTAL_LEN",
    "GeneratedKey",
    "generate_key",
    "VerifiedKey",
    "verify_key",
    "check_scope",
    "InMemoryRateLimiter",
    "RedisTokenBucket",
    "RateLimitGuard",
    "revoke",
    "to_public",
    "validate_scopes",
    "RecommendedCandidate",
    "CandidateRecommender",
    "ROOM_TYPES",
    "ROOM_MEMBER_ROLES",
    "MESSAGE_TYPES",
    "MAX_MESSAGE_LEN",
    "MAX_NAME_LEN",
    "MAX_REACTIONS_PER_MESSAGE",
    "RoomError",
    "NotMemberError",
    "MessageNotFoundError",
    "PermissionDeniedError",
    "Room",
    "RoomMember",
    "RoomMessage",
    "RoomReaction",
    "create_room",
    "get_room",
    "get_room_with_members",
    "list_my_rooms",
    "update_room",
    "archive_room",
    "invite_member",
    "remove_member",
    "leave_room",
    "list_members",
    "post_message",
    "edit_message",
    "delete_message",
    "list_messages",
    "list_thread_replies",
    "search_messages",
    "add_reaction",
    "list_reactions",
    "pin_message",
    "unpin_message",
    "list_pins",
    "mark_read",
    "get_unread_count",
    "get_total_unread_count",
    "list_my_mentions",
    "mark_mention_read",
    "DEFAULT_BUCKET",
    "SIGNED_URL_TTL_SECONDS",
    "FileStorageService",
    "get_file_storage",
    "reset_file_storage",
    "FunnelEvent",
    "FunnelEventTracker",
    "auto_transition",
    "DEFAULT_LIMIT",
    "SubscriptionCriteria",
    "JobPosting",
    "Subscription",
    "JobSubscriptionService",
    "PREF_KEYS",
    "MIN_CONFIDENCE",
    "SOURCE_EXPLICIT",
    "SOURCE_INFERRED",
    "SOURCE_ADMIN",
    "set_pref",
    "get_prefs",
    "get_pref",
    "delete_pref",
    "EXTRACT_PROMPT",
    "infer_prefs_from_text",
    "render_prefs_for_prompt",
    "FieldSpec",
    "resolve_canonical",
    "list_pii_fields",
    "PIIFieldService",
    "get_pii_field_service",
    "pii_encrypted_fields",
    "encrypt_dict",
    "decrypt_dict",
    "DEFAULT_TOKEN_BYTES",
    "DEFAULT_TTL_DAYS",
    "Invitation",
    "generate_invite_token",
    "build_invite_url",
    "create_invitation",
    "accept_invitation",
    "NPS_TARGET",
    "PROGRAM_STATUSES",
    "TOP_PAIN_POINTS_LIMIT",
    "WEEKLY_ACTIVE_TARGET",
    "PilotReport",
    "ProgramStats",
    "compute_nps",
    "create_program",
    "end_program",
    "generate_report",
    "get_program",
    "get_stats",
    "invite",
    "list_programs",
    "CATEGORY_BUG",
    "CATEGORY_COMPLAINT",
    "CATEGORY_DOCS",
    "CATEGORY_FEATURE",
    "CATEGORY_OTHER",
    "CATEGORY_PERFORMANCE",
    "CATEGORY_PRAISE",
    "CATEGORY_PRICING",
    "SUPPORTED_CATEGORIES",
    "CategorizedFeedback",
    "NPSResult",
    "calculate_nps",
    "categorize_feedback",
    "categorize_many",
    "generate_monthly_report",
    "generate_monthly_report_text",
    "PushRecord",
    "PushEngine",
    "AGENT_DESCRIPTIONS_FALLBACK",
    "RealtimeRouter",
    "TranscribeResult",
    "transcribe_audio",
]
