#!/usr/bin/env python3
"""v11.4 R1 — Load seed JSONL into the LOCAL postgres (本地库装载).

Problem this solves
-------------------
``scripts/seed_test_data.py`` only writes ``seed_output/*.jsonl`` by default.
Writing to the DB needs ``--supabase`` + a real ``SUPABASE_URL``/key — but the
local self-contained stack ships with ``SUPABASE_URL=`` *empty* (the backend
self-signs JWT and talks to a local postgres directly). So with no loader, the
1000 candidates / 10 orgs / 5 roles generated by the seed script **never reach
the database**, and the demo falls back to ~24 synthetic rows — directly
violating the 甲方 acceptance hard requirement of "1000 求职者".

This loader reads the JSONL produced by ``seed_test_data.py`` and upserts them
idempotently into the local postgres via ``DATABASE_URL`` (psycopg2, no cloud
Supabase dependency).

What it loads (in FK-safe order)
    1. the seed ``created_by`` user (FK target for candidates / orgs / roles)
    2. organisations
    3. candidates (PII encrypted on write)
    4. roles
    5. matches

Design rules (甲方合同 / review brief):
  * 容错缺字段: schema is introspected at load time. Columns that exist in the
    JSONL but not on the live table are skipped with a WARN (handles the
    001_cloud vs 001_initial drift + experience_score + v11.2 columns). We do
    NOT alter the schema here — the migrations own DDL.
  * 幂等: every upsert is ``ON CONFLICT (id) DO NOTHING``; re-running never
    errors and never duplicates. Also re-running with re-generated JSONL is
    safe (new ids insert, old ids stay).
  * PII (avoid 明文落库): candidate ``email`` / ``phone`` / ``cv_text`` are
    encrypted with the SAME entry resume_parser uses
    (``services.integrations.pii_field_encryption.get_pii_field_service``), so
    the backend can transparently decrypt on read. Values already carrying a
    Fernet token (``gAAAA...``) are written through unchanged (idempotent).
  * 数据主权: no network — pure psycopg2 + the in-repo Fernet PII service.

Usage
-----
    # dry-run (no DB): print row counts + the SQL that would run
    python scripts/load_seed_local.py --dry-run

    # load into the local DB (host port 5432)
    python scripts/load_seed_local.py \
        --database-url postgresql://postgres:postgres@localhost:5432/waibao

    # custom JSONL dir
    python scripts/load_seed_local.py --database-url ... --seed-dir ./seed_output

Exit codes: 0 success / dry-run ok, 1 hard error (bad JSONL, DB error, ...).
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any, Iterable

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------

# FK target for candidates.created_by / roles.created_by / organisations.
# seed_test_data.py stamps every generated row with this fixed talent-partner
# uuid (see seed_output/*.jsonl `created_by`). The local docker stack does NOT
# mount supabase/seed.sql, so this user does not exist in a fresh local DB —
# without it the very first candidate INSERT dies on the FK. We upsert it.
SEED_CREATED_BY_UUID = "024ff6b9-2e5e-419e-b9d2-9ea665c22f17"

DEFAULT_SEED_DIR = Path(__file__).resolve().parent.parent / "seed_output"

# jsonl filename -> table name (load order is enforced by load_all)
JSONL_FILES: list[tuple[str, str]] = [
    ("organisations.jsonl", "organisations"),
    ("candidates.jsonl", "candidates"),
    ("roles.jsonl", "roles"),
    ("matches.jsonl", "matches"),
]

# PII fields to encrypt on write for candidates (resume_parser entry).
# resume_parser._post_process encrypts ["name","email","phone"] of the LLM
# `basic` dict; here we encrypt the candidate TABLE columns email/phone/cv_text
# via the same get_pii_field_service (resolves cv_text as alias of resume_text).
CANDIDATE_PII_FIELDS = ["email", "phone", "cv_text"]

# Fields we never persist to the DB (seed-only metadata / bookkeeping).
DROP_FIELDS = {"_meta"}

# Fields that are JSONB on every table — serialized with json.dumps so psycopg2
# sends them as jsonb via its adaptation of str->json. (psycopg2 adapts Python
# str into text; for jsonb columns we wrap with psycopg2.extras.Json instead at
# bind time — handled in _bind_value.)
JSONB_HINT = {
    "organisations": {"qualifications"},
    "candidates": {"skills", "experience", "salary_expectation", "industries",
                   "sources", "extraction_flags"},
    "roles": {"required_skills", "preferred_skills", "salary_band"},
    "matches": {"skill_overlap", "strengths", "gaps", "scoring_breakdown"},
}


# ---------------------------------------------------------------------------
# PII encryption (reuse resume_parser's entry — do NOT reimplement Fernet)
# ---------------------------------------------------------------------------
_pii_service: Any = None
_pii_unavailable_reason: str | None = None


def _get_pii_service() -> Any:
    """Lazily import the in-repo PII field service (resume_parser's entry).

    Returns None if the backend package / cryptography is not importable on the
    host running the loader; callers must then WARN and fall back to writing the
    value as-is (plaintext) — logged loudly so the operator can fix the env.
    """
    global _pii_service, _pii_unavailable_reason
    if _pii_service is not None:
        return _pii_service
    if _pii_unavailable_reason is not None:
        return None
    backend_dir = Path(__file__).resolve().parent.parent / "backend"
    if str(backend_dir) not in sys.path:
        sys.path.insert(0, str(backend_dir))
    try:
        from services.integrations.pii_field_encryption import (  # type: ignore
            get_pii_field_service,
        )
        _pii_service = get_pii_field_service()
        return _pii_service
    except Exception as exc:  # noqa: BLE001 — degrade gracefully, warn loudly
        _pii_unavailable_reason = repr(exc)
        return None


def encrypt_pii_row(row: dict[str, Any], fields: Iterable[str]) -> dict[str, Any]:
    """Encrypt the given PII fields in ``row`` in place-safe copy.

    Uses the same service resume_parser uses; already-encrypted values
    (``gAAAA...``) are passed through unchanged (the service's
    ``_looks_like_ciphertext`` heuristic handles idempotency).
    """
    svc = _get_pii_service()
    if svc is None:
        # Fallback: write as-is. This is a degraded path — surface it to the
        # operator so plaintext PII never lands silently.
        return dict(row)
    return svc.encrypt_pii_fields(dict(row), list(fields))


# ---------------------------------------------------------------------------
# JSONL reading
# ---------------------------------------------------------------------------
def read_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as fh:
        for lineno, line in enumerate(fh, 1):
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError as exc:
                raise SystemExit(
                    f"[load_seed_local] {path.name}:{lineno}: invalid JSON: {exc}"
                ) from exc
            if isinstance(obj, dict):
                rows.append(obj)
    return rows


def clean_row(row: dict[str, Any]) -> dict[str, Any]:
    """Strip seed-only bookkeeping fields we never persist."""
    return {k: v for k, v in row.items() if k not in DROP_FIELDS}


# ---------------------------------------------------------------------------
# Schema introspection (tolerate column drift between migrations)
# ---------------------------------------------------------------------------
def fetch_columns(cur, table: str) -> set[str]:
    """Return the set of column names that actually exist on ``table``."""
    cur.execute(
        """
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = %s
        """,
        (table,),
    )
    return {r[0] for r in cur.fetchall()}


# ---------------------------------------------------------------------------
# Seed user (FK target)
# ---------------------------------------------------------------------------
def ensure_seed_user(cur, dry_run: bool) -> None:
    """Upsert the talent-partner user that every seed row points at via
    ``created_by``. Without it, candidate/role/org inserts violate the FK.

    The local docker stack mounts only supabase/migrations/*.sql (NOT
    supabase/seed.sql), so this user is absent in a fresh local DB.
    """
    email = "seed-partner@waibao.local"
    if dry_run:
        print(f"  [dry-run] upsert seed user {SEED_CREATED_BY_UUID} ({email})")
        return

    # users.email is itself a PII-encrypted column in the registry, but for the
    # local self-contained demo a deterministic synthetic address is fine; we
    # encrypt it through the same service so the column stays consistent with
    # how the backend writes/reads it.
    enc_email = email
    svc = _get_pii_service()
    if svc is not None:
        try:
            enc_email = svc.encrypt_pii(email, "email")
        except Exception:  # noqa: BLE001
            enc_email = email

    cur.execute(
        """
        INSERT INTO users (id, email, first_name, last_name, role, is_active)
        VALUES (%s, %s, %s, %s, %s, TRUE)
        ON CONFLICT (id) DO NOTHING
        """,
        (SEED_CREATED_BY_UUID, enc_email, "Seed", "Partner", "talent_partner"),
    )


# ---------------------------------------------------------------------------
# Upsert builder (column-tolerant)
# ---------------------------------------------------------------------------
def build_upsert(table: str, row: dict[str, Any], live_cols: set[str]) -> str | None:
    """Build a parameterised ``INSERT ... ON CONFLICT (id) DO NOTHING`` for the
    columns of ``row`` that exist on the live table. Returns None if no usable
    columns survive (caller skips + warns). Does NOT interpolate values — only
    placeholders, so SQL-injection-safe.
    """
    cols = [c for c in row.keys() if c in live_cols]
    if not cols:
        return None
    placeholders = ", ".join(["%s"] * len(cols))
    col_list = ", ".join(cols)
    return (
        f"INSERT INTO {table} ({col_list}) VALUES ({placeholders}) "
        f"ON CONFLICT (id) DO NOTHING"
    )


def _bind_value(table: str, col: str, value: Any):
    """Wrap dict/list values as jsonb for psycopg2. Scalars pass through."""
    if isinstance(value, (dict, list)):
        try:
            from psycopg2.extras import Json  # local import; only on real loads
            return Json(value)
        except ImportError:
            return json.dumps(value, ensure_ascii=False)
    return value


# ---------------------------------------------------------------------------
# Per-table loaders
# ---------------------------------------------------------------------------
def load_table(
    cur,
    table: str,
    rows: list[dict[str, Any]],
    live_cols: set[str],
    *,
    dry_run: bool,
    pii_fields: Iterable[str] = (),
) -> dict[str, int]:
    inserted = 0
    skipped_no_cols = 0
    dropped_cols: set[str] = set()

    for raw in rows:
        row = clean_row(raw)

        # record which JSONL fields the live table is missing (warn once-ish)
        for c in row.keys():
            if c not in live_cols:
                dropped_cols.add(c)

        if pii_fields:
            row = encrypt_pii_row(row, pii_fields)

        sql = build_upsert(table, row, live_cols)
        if sql is None:
            skipped_no_cols += 1
            continue

        if dry_run:
            inserted += 1
            continue

        # bind in the same column order build_upsert used (intersect with live)
        cols = [c for c in row.keys() if c in live_cols]
        values = [_bind_value(table, c, row.get(c)) for c in cols]
        try:
            cur.execute(sql, values)
        except Exception as exc:  # noqa: BLE001 — per-row resilience
            print(
                f"  [WARN] {table}: failed row id={row.get('id')!r}: {exc}",
                file=sys.stderr,
            )
            # re-raise only FK/structural hard errors? We warn + continue so a
            # single bad row doesn't abort the whole seed load.
            continue
        if cur.rowcount and cur.rowcount > 0:
            inserted += 1

    return {
        "inserted": inserted,
        "skipped_no_cols": skipped_no_cols,
        "dropped_columns": len(dropped_cols),
        "dropped_column_names": sorted(dropped_cols),
    }


def load_all(
    cur,
    seed_dir: Path,
    *,
    dry_run: bool,
) -> dict[str, Any]:
    report: dict[str, Any] = {}

    # 0. seed user (FK target) — before any org/role/candidate
    ensure_seed_user(cur, dry_run)

    # 1. organisations (no PII, no created_by FK in 001, but keep order)
    # 2. candidates (PII) — before matches (matches FK -> candidates)
    # 3. roles — before matches (matches FK -> roles)
    # 4. matches (FK -> candidates + roles)
    order = [
        ("organisations.jsonl", "organisations", ()),
        ("candidates.jsonl", "candidates", CANDIDATE_PII_FIELDS),
        ("roles.jsonl", "roles", ()),
        ("matches.jsonl", "matches", ()),
    ]

    for fname, table, pii_fields in order:
        path = seed_dir / fname
        if not path.exists():
            print(f"  [SKIP] {fname} not found in {seed_dir}", file=sys.stderr)
            report[table] = {"missing": True}
            continue
        rows = read_jsonl(path)
        if dry_run:
            live_cols = set()  # not connecting; assume all JSONL cols map
            # still report what would be dropped vs a synthetic full col set
            live_cols = _dry_run_cols(table)
        else:
            live_cols = fetch_columns(cur, table)
            if not live_cols:
                print(
                    f"  [WARN] table {table} does not exist in DB — skipping "
                    f"(migration not applied?)",
                    file=sys.stderr,
                )
                report[table] = {"missing_table": True, "jsonl_rows": len(rows)}
                continue
        res = load_table(
            cur, table, rows, live_cols,
            dry_run=dry_run, pii_fields=pii_fields,
        )
        report[table] = res

    return report


# ---------------------------------------------------------------------------
# Dry-run column map (what we *expect* to find after migrations)
# ---------------------------------------------------------------------------
def _dry_run_cols(table: str) -> set[str]:
    """Approximate the post-migration column set for dry-run reporting.

    In dry-run we don't connect, so we project the union of base + v11.2 cols
    that the migrations define. This is only for the dropped-column WARN; the
    real load introspects the live DB.
    """
    common = {
        "organisations": {
            "id", "name", "industry", "website", "location", "description",
            "created_at", "updated_at",
        },
        "candidates": {
            "id", "first_name", "last_name", "email", "phone", "location",
            "linkedin_url", "skills", "experience", "seniority",
            "salary_expectation", "availability", "industries", "cv_text",
            "profile_text", "sources", "extraction_confidence",
            "extraction_flags", "education", "experience_years",
            "created_at", "updated_at", "created_by",
            # v11.2 (064_identity_compensation)
            "identity_status", "id_card_status", "education_doc_status",
            "resume_status", "social_insurance_expectation", "travel_tolerance",
            "identity_verified_at",
        },
        "roles": {
            "id", "title", "description", "organisation_id", "required_skills",
            "preferred_skills", "seniority", "salary_band", "location",
            "remote_policy", "industry", "status", "created_at", "created_by",
            # v11.2 (064_identity_compensation)
            "offers_social_insurance", "offers_housing_fund", "travel_required",
        },
        "matches": {
            "id", "candidate_id", "role_id", "overall_score",
            "structured_score", "semantic_score", "experience_score",
            "skill_overlap", "confidence", "explanation", "strengths", "gaps",
            "recommendation", "scoring_breakdown", "model_version", "status",
            "created_at",
        },
    }
    return common.get(table, set())


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------
def print_report(report: dict[str, Any], *, dry_run: bool) -> None:
    verb = "would insert" if dry_run else "inserted"
    print()
    print("=" * 60)
    print(f"  {'DRY-RUN' if dry_run else 'LOAD'} REPORT")
    print("=" * 60)
    total_c = total_r = total_m = total_o = 0
    for table, res in report.items():
        if res.get("missing"):
            print(f"  {table:14s}  [missing jsonl — skipped]")
            continue
        if res.get("missing_table"):
            print(f"  {table:14s}  [TABLE MISSING — {res.get('jsonl_rows',0)} jsonl rows not loaded]")
            continue
        n = res.get("inserted", 0)
        if table == "candidates":
            total_c = n
        elif table == "roles":
            total_r = n
        elif table == "matches":
            total_m = n
        elif table == "organisations":
            total_o = n
        dropped = res.get("dropped_column_names") or []
        skip = res.get("skipped_no_cols", 0)
        line = f"  {table:14s}  {verb} {n}"
        if skip:
            line += f"  (skipped {skip} w/ no live cols)"
        if dropped:
            line += f"\n                  dropped cols (not in live table): {dropped}"
        print(line)
    print("-" * 60)
    print(f"  organisations: {total_o} | candidates: {total_c} | "
          f"roles: {total_r} | matches: {total_m}")
    if dry_run:
        print("  (dry-run: nothing was written)")
    print("=" * 60)


# ---------------------------------------------------------------------------
# Entrypoint
# ---------------------------------------------------------------------------
def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="Load seed_output/*.jsonl into the local postgres (v11.4 R1).",
    )
    ap.add_argument(
        "--database-url",
        default=os.environ.get("DATABASE_URL", ""),
        help="psycopg2 DATABASE_URL, e.g. "
             "postgresql://postgres:postgres@localhost:5432/waibao "
             "(falls back to $DATABASE_URL).",
    )
    ap.add_argument(
        "--seed-dir",
        default=str(DEFAULT_SEED_DIR),
        help=f"directory with the JSONL files (default: {DEFAULT_SEED_DIR}).",
    )
    ap.add_argument(
        "--dry-run",
        action="store_true",
        help="Do not connect to the DB. Print row counts + dropped columns + "
             "the seed-user upsert that would run.",
    )
    args = ap.parse_args(argv)

    seed_dir = Path(args.seed_dir)
    if not seed_dir.is_dir():
        print(f"[load_seed_local] seed dir not found: {seed_dir}", file=sys.stderr)
        return 1

    # warn the operator about the PII fallback path up front
    if _get_pii_service() is None:
        print(
            "[load_seed_local] WARNING: backend PII service unavailable "
            f"({_pii_unavailable_reason}). Candidate email/phone/cv_text will "
            "be written in PLAINTEXT. Fix by running with the backend deps on "
            "PYTHONPATH (or set PII_ENCRYPTION_KEY).",
            file=sys.stderr,
        )

    if args.dry_run:
        print(f"[load_seed_local] DRY-RUN against {seed_dir}")
        report = load_all(None, seed_dir, dry_run=True)
        print_report(report, dry_run=True)
        return 0

    if not args.database_url:
        print(
            "[load_seed_local] no --database-url and $DATABASE_URL is empty. "
            "Pass --database-url ... or run with --dry-run.",
            file=sys.stderr,
        )
        return 1

    try:
        import psycopg2
    except ImportError:
        print(
            "[load_seed_local] psycopg2 not installed on this host. "
            "Install psycopg2-binary, or run inside the backend container.",
            file=sys.stderr,
        )
        return 1

    print(f"[load_seed_local] connecting to DB ...")
    try:
        conn = psycopg2.connect(args.database_url)
    except Exception as exc:  # noqa: BLE001
        print(f"[load_seed_local] DB connect failed: {exc}", file=sys.stderr)
        return 1

    try:
        conn.autocommit = False
        with conn.cursor() as cur:
            report = load_all(cur, seed_dir, dry_run=False)
        conn.commit()
    except Exception as exc:  # noqa: BLE001
        conn.rollback()
        print(f"[load_seed_local] load FAILED (rolled back): {exc}", file=sys.stderr)
        return 1
    finally:
        conn.close()

    print_report(report, dry_run=False)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
