[project]
id = "recruittech-local"
name = "RecruitTech PoC"

[api]
enabled = true
port = 54321
schemas = ["public"]

[db]
port = 54322
major_version = 15

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000"]
jwt_expiry = 3600

[auth.email]
enable_signup = true
enable_confirmations = false
